export const PLANNER_STORE_CONSTANTS = {
  ADD_ITEM: "ADD_ITEM",
  EDIT_ITEM: "EDIT_ITEM",
  DELETE_ITEM: "DELETE_ITEM",
  ADD_LAYER: "ADD_LAYER",
  SET_CURRENT_LAYER: "SET_CURRENT_LAYER",
  UPDATE_CANVAS: "UPDATE_CANVAS",
};
